# SITE CONFIGURATION
title: Wilson Walks # your site title
author: James Stocker # You :P
description: > # Meta description of Homepage
  I'm a dog walker in Middlewood, near Hillsborough, Sheffield UK
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rumbles.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Helen Wilson
  links:
    - https://www.facebook.com/wilsonwalkspets/
    - https://www.instagram.com/wilsonwalkspets/

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  An experienced dog walker in Middlewood, North Sheffield, starting my own business in December 2018

hero_img: posts/wilson_walks.jpg
logo: posts/logo.png

email: helen@wilsonwalks.dog # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
instagram_username: wilsonwalkspets # replace with your_instagram_username or comment to remove link from footer
facebook_username: wilsonwalkspets

#disqus:
#  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
